project:
  type: website
  output-dir: docs      # use docs/ for githubpages, other cases use _site/
  render:
#    - "*.{qmd,R,py}"
    - "*.qmd"           # render all *.qmd files
    - "!site/this_dir/" # don't render a directory
    
    #- "!call_scripts/" # don't render a directory
  #pre-render: Rscript prerender.R #load_libraries.R
  # after rendering completes, script that removes .R files from the docs/ folder.
  # post-render: Rscript cleanup/clean_docs_dir.R

  #resources:
  #  - "webr-serviceworker.js"
  #  - "webr-worker.js"
  
  #resources:
  #  - figs/    # ensures that the .R files in figs/ are rendered in a website build
  
  # settings for previewing the website
  preview:
    port: 1670
    browser: true
    navigate: true

website:
  title: "PSYC167 Group Project - CPS" 
  
  # site-url: ""
  # add optional favicon 
  # favicon: "website_files/images/myfavicon.png"

  # add optional page footer
  page-footer:
    # not necessary
    #center: |
      #[contact me](myemail@mydomain.com)
    
    # not necessary
    left: | 
      made with [Quarto](https://quarto.org)
      
    # not necessary
    right: |
      [GitHub Repo](https://github.com/slicesofdata/cps-167-2025)

    # add optional background for footer
    background: "black"
  # add optional logo
  # logo: "website_files/images/logo.png"  # path to your logo image
  

  # add webpage description
  #description: ""

  navbar:
    left:
      # the index file
      #- text: "Introduction" # use empty string to be blank
       # href: index.qmd

      # adding another page
      - text: "Main Finding" 
        href: pages/veteran_status.qmd  # use a meaningful name 

      # adding a tab with dropdown menu
      - text: "Supplementary Factors"
        menu:
          - text: "Education"
            href: pages/education.qmd 
          - text: "Race"
            href: pages/my_third_page.qmd  
       
    right:
      - about.qmd     # to have about page here instead 
      
      # not necessary
      - icon: github
        href: https://github.com/slicesofdata/cps-167-2025  # omit for multiple users
        
      # not necessary
      #- text: "@myxhandle"
      #  href: https://x.com/myxhandle
      #  aria-label: X (formerly Twitter)

format:
  html:
    theme: 
      light: [cosmo, styles/example-light.scss] # location of light theme
      dark: [cosmo, styles/example-dark.scss]   # location of dark theme

    toc: true
    #page-layout: full
    # add option for other fonts
    include-in-header: "fonts/fontawesome.html"
    #mainfont: arial #Nunito
    #fontsize: 1.1rem # 1.2rem


# for branding
#brand:
  #light: brand/light.yml
  #dark: brand/dark.yml

# set quarto optional editor preference: source or visual
#editor: source

